version: '3.8'

services:
  postgres:
    image: postgres:13.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: backend-base-db
      POSTGRES_PASSWORD: password
